DonutWare/Fladder

- lib/screens/shared/media/components/poster_image.dart
- lib/widgets/shared/status_card.dart
Slight regression I didn't notice.
> [Bugfix] Made the status card 1:1 ratio

- altstore.json
Add 0.2.6 to the AltStore repository
Issue Number: No issue
*No screenshots*
> Add 0.2.6 to AltStore repo

- lib/screens/collections/add_to_collection.dart
- lib/screens/metadata/identifty_screen.dart
- lib/screens/metadata/refresh_metadata.dart
- lib/screens/playlists/add_to_playlists.dart
- lib/screens/settings/settings_list_tile.dart
- lib/screens/settings/settings_scaffold.dart
- lib/screens/settings/widgets/settings_label_divider.dart
- lib/screens/shared/adaptive_dialog.dart
- lib/screens/shared/default_titlebar.dart
- lib/screens/shared/detail_scaffold.dart
- lib/screens/syncing/sync_item_details.dart
- lib/screens/syncing/widgets/sync_markedfordelete.dart
- lib/screens/video_player/video_player_controls.dart
- lib/util/adaptive_layout.dart
- lib/widgets/navigation_scaffold/components/navigation_body.dart
- lib/widgets/shared/alert_content.dart
- lib/widgets/shared/item_actions.dart
- lib/widgets/shared/modal_bottom_sheet.dart
This fixes a bunch of padding issues, and also improves padding in other areas. 
Issue Number: #29
> fix: padding issues

- lib/screens/login/login_screen.dart
> fix(mobile): login screen disable auto-correct input fields

- lib/providers/settings/video_player_settings_provider.dart
- lib/screens/video_player/video_player.dart
- lib/screens/video_player/video_player_controls.dart
- lib/widgets/navigation_scaffold/components/navigation_body.dart
- lib/widgets/navigation_scaffold/components/navigation_drawer.dart
- lib/widgets/shared/full_screen_button.dart
- lib/widgets/shared/full_screen_button_web.dart
Adds the full screen toggle to web and the volume slider.
fix: small fixes for desktop padding
fix: only reload widgets when the content has changed
Issue Number: #28
> feature(web): Added full-screen button and volume slider 

- lib/models/credentials_model.dart
Use updated auth header for jellyfin authentication
Using deprecated auth headers
Resolves #61
> fix: Updated auth header

- lib/l10n/app_uk.arb
Adds Ukrainian to the list of supported languages. I'd like to extend a huge thank-you to @stanol for providing the translation.
Resolves #60
> feat: Add Ukrainian translation

- lib/l10n/app_en.arb
- lib/models/settings/home_settings_model.dart
- lib/models/syncing/i_synced_item.dart
- lib/models/syncing/i_synced_item.g.dart
- lib/models/syncing/sync_item.dart
- lib/models/syncing/sync_item.freezed.dart
- lib/providers/sync_provider.dart
- lib/screens/syncing/sync_item_details.dart
- lib/screens/syncing/sync_list_item.dart
- lib/screens/syncing/sync_widgets.dart
- lib/screens/syncing/widgets/sync_status_overlay.dart
- lib/screens/syncing/widgets/synced_episode_item.dart
- linux/CMakeLists.txt
- macos/Runner/Configs/AppInfo.xcconfig
- windows/runner/Runner.rc
This fixes some small issue with syncing items. Mainly the time it took to start syncing. And cancelled/failed items not being cleaned up.
Resolves #10
> fix: Sync leaving left over temp files

- lib/l10n/app_en.arb
- lib/screens/collections/add_to_collection.dart
- lib/screens/playlists/add_to_playlists.dart
Add some missing translations
Resolves #51
> fix: Added some missing translations

- lib/l10n/app_en.arb
- lib/models/items/media_streams_model.dart
- lib/models/media_playback_model.dart
- lib/screens/book_viewer/book_viewer_controls.dart
- lib/screens/photo_viewer/photo_viewer_controls.dart
- lib/screens/shared/passcode_input.dart
- lib/screens/video_player/components/video_player_options_sheet.dart
- lib/screens/video_player/components/video_subtitle_controls.dart
- lib/screens/video_player/video_player_controls.dart
- lib/widgets/shared/full_screen_button.dart
- lib/widgets/shared/full_screen_button_web.dart
Fixed keyboard controls for desktop and the controls not auto-hiding
Also fixes some translations
Resolves #77
> fix: Keyboard controls and translations

- lib/screens/video_player/components/video_player_seek_indicator.dart
- lib/screens/video_player/video_player_controls.dart
Added a seek indicator for desktop
> feature(Desktop: Added seek indicator

- .github/release.yml
- .github/workflows/build.yml
> chore: automate releases

- .github/workflows/checks.yaml
- lib/widgets/shared/full_screen_button.dart
> chore: improved dart analyzer

- lib/screens/video_player/components/video_volume_slider.dart
- lib/screens/video_player/video_player_controls.dart
Fixes text that had no theme color applied
Resolves #83
> fix: Video player - Use theme to get the correct text color

- lib/screens/shared/media/banner_play_button.dart
Fix  a small issue with the media banner buttons
> fix: small alignment issue media banner buttons

- lib/l10n/app_en.arb
- lib/models/settings/video_player_settings.dart
- lib/models/settings/video_player_settings.freezed.dart
- lib/models/settings/video_player_settings.g.dart
- lib/providers/settings/video_player_settings_provider.dart
- lib/providers/shared_provider.dart
- lib/screens/photo_viewer/photo_viewer_controls.dart
- lib/screens/settings/player_settings_page.dart
- lib/screens/settings/widgets/settings_message_box.dart
- lib/screens/video_player/components/video_player_next_wrapper.dart
- lib/screens/video_player/video_player.dart
- lib/widgets/navigation_scaffold/components/floating_player_bar.dart
- lib/widgets/shared/progress_floating_button.dart
Adds a next-up preview when the video is about to end.
Provides options to disable/enable the functionality. 
Also skips the video after 30 seconds
> feature: Auto next-up preview, skip to next in queue.

- lib/l10n/app_en.arb
- lib/screens/video_player/components/video_player_options_sheet.dart
Adds a simple playback rate that persists for the sessions only
Resolves #78
> feature: Added playback rate to video player options

- lib/screens/book_viewer/book_viewer_controls.dart
- lib/screens/photo_viewer/photo_viewer_controls.dart
- lib/screens/shared/passcode_input.dart
- lib/screens/video_player/components/video_player_seek_indicator.dart
- lib/screens/video_player/components/video_subtitles.dart
- lib/screens/video_player/video_player_controls.dart
- lib/util/input_handler.dart
The previous implementation while it did work. Keys where being send to parent widgets as well. Causing invisible/out of view items to be clicked and interacted with.
> fix: Improve keyboard input handling

- lib/screens/login/lock_screen.dart
> feature(Lock-screen): Replaced login button with a floating action button

- .vscode/settings.json
- lib/models/items/trick_play_model.dart
- lib/models/playback/direct_playback_model.dart
- lib/models/playback/playback_model.dart
- lib/models/playback/transcode_playback_model.dart
- lib/providers/service_provider.dart
- lib/screens/video_player/components/video_progress_bar.dart
- lib/screens/video_player/video_player_controls.dart
- lib/widgets/shared/trick_play_image.dart
> chore: Renaming of Trickplay -> TrickPlay and other cleanups

- lib/screens/metadata/info_screen.dart
- lib/screens/shared/default_titlebar.dart
- lib/screens/video_player/components/video_player_next_wrapper.dart
- lib/screens/video_player/components/video_player_options_sheet.dart
- lib/screens/video_player/video_player_controls.dart
The statusbar was hidden when hovering over it with the mouse.
> fix(Desktop): Fixed some of desktop specific controls

- lib/models/items/episode_model.dart
Fixes sorting of seasons in episode row
> fix: Fixed season sorting episode view

- lib/models/collection_types.dart
- lib/models/view_model.dart
Default collectioType is now Folders
Resolves #139
> bugfix: Fixed all library types being sorted as Movies

- android/app/src/main/AndroidManifest.xml
- lib/main.dart
- lib/models/items/chapters_model.dart
- lib/models/items/images_models.dart
- lib/screens/library_search/widgets/suggestion_search_bar.dart
- lib/screens/login/login_screen.dart
- lib/screens/login/login_user_grid.dart
- lib/screens/metadata/identifty_screen.dart
- lib/screens/photo_viewer/photo_viewer_screen.dart
- lib/screens/photo_viewer/simple_video_player.dart
- lib/screens/settings/widgets/subtitle_editor.dart
- lib/screens/shared/user_icon.dart
- lib/screens/video_player/components/video_player_queue.dart
- lib/stubs/web/lib_mdk_web.dart
- lib/stubs/web/smtc_web.dart
- lib/util/adaptive_layout.dart
- lib/util/custom_cache_manager.dart
- lib/util/debug_banner.dart
- lib/widgets/navigation_scaffold/components/fladder_app_bar.dart
- lib/widgets/navigation_scaffold/navigation_scaffold.dart
- lib/wrappers/media_control_wrapper.dart
- lib/wrappers/players/base_player.dart
- lib/wrappers/players/lib_mdk.dart
- lib/wrappers/players/lib_mpv.dart
- linux/flutter/generated_plugins.cmake
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugins.cmake
Update the media-kit(MPV) dependency
Fix Simple Video Player not properly initializing
Enabled impeller for Android
> chore: Update MPV package to latest version

- lib/screens/settings/client_settings_page.dart
- lib/screens/settings/player_settings_page.dart
- lib/screens/video_player/components/video_player_options_sheet.dart
> fix: Player orientation title

- lib/l10n/app_en.arb
- lib/models/items/media_segments_model.dart
- lib/screens/video_player/components/video_player_controls_extras.dart
- lib/screens/video_player/video_player_controls.dart
> feature: Handle all media segments skipping

- lib/l10n/app_en.arb
- lib/main.dart
- lib/providers/crash_log_provider.dart
- lib/screens/crash_screen/crash_screen.dart
- lib/screens/settings/about_settings_page.dart
- lib/screens/settings/client_settings_page.dart
This implements a basic option to view crash logs. Used for local logging of any widgets/players not working like expected.
Resolves #180
> chore: Added simple option to view/copy crash-logs locally

- lib/providers/items/episode_details_provider.dart
Fix a small regresion of episodes not loading when synced and in airplane mode.
Resolves #189
> fix: Synced episode information not loading

- lib/screens/photo_viewer/photo_viewer_screen.dart
- lib/screens/shared/detail_scaffold.dart
- lib/util/fladder_image.dart
- lib/widgets/shared/trick_play_image.dart
Fix over-sharpening of images throughout the app
Resolves #203
> fix: Over-sharpened images from filter quality

- lib/screens/shared/default_title_bar.dart
Cleanup full-screen/maximize behaviour
Resolves #198
> fix(Desktop): Simplified full-screen/maximize behaviour

- lib/wrappers/media_control_wrapper.dart
Implement pause behaviour
Resolves #212
> fix: Media-control pausing of media

- lib/models/items/images_models.dart
- lib/models/items/item_shared_models.dart
- lib/providers/image_provider.dart
Some images where incorrectly handle as strings while being null
Resolves #224
> fix: Improve null handling when parsing image urls

- lib/l10n/app_en.arb
- lib/models/items/episode_model.dart
- lib/screens/shared/media/episode_posters.dart
Improve UI for episode status (missing,unaired) indicators. Also added translations
> feature: Improve episode status indicators

- lib/models/items/media_streams_model.dart
- lib/models/video_stream_model.dart
Jellyfin can also send back a "null" index when no subtitles should be selected by default. This now properly parses this.
Resolves #128
> fix: Properly parse null values api

- lib/l10n/app_en.arb
- lib/models/items/episode_model.dart
- lib/models/items/item_stream_model.dart
- lib/models/items/media_streams_model.dart
- lib/models/items/movie_model.dart
- lib/models/playback/playback_model.dart
- lib/models/video_stream_model.dart
- lib/providers/items/episode_details_provider.dart
- lib/providers/items/movies_details_provider.dart
- lib/screens/details_screens/components/media_stream_information.dart
- lib/screens/details_screens/episode_detail_screen.dart
- lib/screens/details_screens/movie_detail_screen.dart
- lib/screens/shared/media/components/next_up_episode.dart
Add the option to select a version if available. Small re-work on streamModels to better support version selection
Resolves #227
> feature: Version selection

- lib/l10n/app_en.arb
- lib/models/items/media_segments_model.dart
- lib/models/settings/video_player_settings.dart
- lib/models/settings/video_player_settings.freezed.dart
- lib/models/settings/video_player_settings.g.dart
- lib/providers/items/movies_details_provider.g.dart
- lib/screens/settings/player_settings_page.dart
- lib/screens/video_player/components/video_player_controls_extras.dart
- lib/screens/video_player/video_player_controls.dart
Adds different user selectable actions for media segments
> feature: Add actions for media segments

- lib/screens/photo_viewer/simple_video_player.dart
- lib/screens/shared/media/components/item_logo.dart
- lib/screens/shared/media/components/media_header.dart
- lib/screens/video_player/video_player_controls.dart
- lib/util/fladder_image.dart
Fixed small bug causing full-screen buttons to not show in desktop mode.
Added show/movie logo to the video player
Resolves #237
> fix: Improved and fixed some of the videoPlayer controls

- lib/models/settings/subtitle_settings_model.dart
> fix: Hide subtitles with empty text

- lib/fake/fake_jellyfin_open_api.dart
- lib/models/playback/playback_model.dart
- lib/util/bitrate_helper.dart
- lib/util/item_base_model/play_item_helpers.dart
Implemented video-playback for the "fake" server for easier testing.
> chore: Play BigBuckBunny for every fake item

- lib/main.dart
- lib/screens/shared/media/season_row.dart
- lib/stubs/web/smtc_web.dart
- lib/util/localization_helper.dart
- lib/wrappers/media_control_wrapper.dart
Fixes windows not reporting back to the media controls
> fix: Windows media controls

- lib/models/settings/subtitle_settings_model.dart
Small improvement for smaller devices
Resolves #255
> feature: improve corner radius subtitle background

- lib/providers/views_provider.dart
No longer artfiically hide some collections
Resolves #286
> fix: Show any enabled libraries in home screen

- lib/screens/photo_viewer/photo_viewer_controls.dart
- lib/widgets/shared/progress_floating_button.dart
Keep screen alive during slideshow
Added full-screen toggle
> feature(PhotoViewer): Keep screen alive during slideshow

- lib/screens/video_player/video_player_controls.dart
Fixes small regression and older bug
Resolves #306 and #257
> fix(Desktop/Web): Mouse not hiding and controls not appearing (web)

- lib/screens/library_search/widgets/library_saved_filters.dart
Use inkwell instead of shared FlatButton
Resolves #337
> fix: Filter buttons not working

- lib/providers/video_player_provider.dart
- lib/wrappers/media_control_wrapper.dart
Fixes progressbar not updating when paused.
Reduce ui rebuilds when updating playback position
Resolves #333
> fix: Update playback position when paused

- lib/models/items/media_segments_model.dart
- lib/screens/video_player/components/video_player_controls_extras.dart
- lib/screens/video_player/video_player_controls.dart
Improves media segment visibility logic. If the segment is longer then 2 minutes we hide the button anyway.
Resolves #320
> feat: Improve segments visibility logic

- lib/l10n/app_en.arb
- lib/models/settings/client_settings_model.dart
- lib/models/settings/client_settings_model.freezed.dart
- lib/models/settings/client_settings_model.g.dart
- lib/providers/sync/background_download_provider.dart
- lib/providers/sync/background_download_provider.g.dart
- lib/screens/settings/client_sections/client_settings_download.dart
Adds the option for setting the max concurrent downloads when syncing items
Resolves #336
> feat: Add max concurrent downloads to settings

- lib/models/library_filters_model.g.dart
- lib/models/library_search/library_search_model.dart
- lib/models/library_search/library_search_model.mapper.dart
- lib/models/library_search/library_search_options.dart
- lib/providers/items/book_details_provider.dart
Use sortName instead of name to fetch by item name
> fix: Use sortName instead of name for searches/library views

- lib/l10n/app_en.arb
- lib/models/items/episode_model.dart
- lib/models/playback/playback_model.dart
- lib/models/playback/playback_options_dialogue.dart
- lib/models/video_stream_model.dart
- lib/screens/shared/adaptive_dialog.dart
- lib/screens/video_player/components/video_playback_information.dart
- lib/screens/video_player/video_player_controls.dart
- lib/util/item_base_model/play_item_helpers.dart
When syncing a item for offline playback ask the user if the item should be played in offline mode.
Resolves #285
> feature: Ask for playback type when media is downloaded

- lib/l10n/app_en.arb
- lib/models/settings/client_settings_model.dart
- lib/models/settings/client_settings_model.freezed.dart
- lib/models/settings/client_settings_model.g.dart
- lib/screens/settings/client_sections/client_settings_visual.dart
- lib/widgets/navigation_scaffold/components/background_image.dart
Adds the ability to toggle on/off background images
Resolves #364
> feature: Add option to disable background images

- lib/l10n/app_en.arb
- lib/models/settings/client_settings_model.dart
- lib/models/settings/client_settings_model.freezed.dart
- lib/models/settings/client_settings_model.g.dart
- lib/screens/settings/client_sections/client_settings_visual.dart
- lib/screens/shared/detail_scaffold.dart
- lib/screens/shared/nested_scaffold.dart
- lib/widgets/navigation_scaffold/components/background_image.dart
Visual improvement for the current background options
> feat: Add on/off/blurred options to the background image

- lib/l10n/app_en.arb
- lib/screens/video_player/components/video_player_volume_indicator.dart
- lib/screens/video_player/components/video_volume_slider.dart
- lib/screens/video_player/video_player_controls.dart
- lib/util/input_handler.dart
Changes the scroll volume behavior to the entire screen.
Adds a indicator the screen when changing the volume
> feat: Add volume indicator and scroll handles on entire screen
