- lib/screens/shared/media/components/poster_image.dart
- lib/screens/shared/media/season_row.dart
- lib/widgets/shared/status_card.dart
Fix the error when display large numbers #5 
Example: 
The numbers in the example image was random generated.
> [Bugfix] Fix display large numbers

- lib/routes/auto_router.dart
- lib/screens/login/login_screen.dart
- lib/screens/settings/settings_screen.dart
Fixes a small bug where the user could navigate back to the splashscreen when starting the app.
Also fixes switching users and going back from the login screen.
> [Bugfix] Mobile - Fixed navigating back to splash screen

- .github/workflows/build.yml
Hi there,
I managed to boil down the compilation issues to only Android and iOS, the former returning the error `Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.` (the Kotlin version was also out of date, spewing dependency errors into the run log, that has since been fixed, I hope), and the latter returning the `No Team Found in Archive` error during the IPA export. The main build workflow has been deleted and replaced with separate workflows for compiling on desktop, mobile and GitHub Pages.
Feel free to test out my changes and if you have any issues, let me know. If you still want to collate the GH actions into a single file, I'd be …
> Add libmpv-dev to Linux workflow to fix compilation

- README.md
Added a button that allows quick addition of the repo to AltStore from an iDevice. Due to the README not allowing 'altstore://' links, I had to do it through a link shortener. The non shortened URL is:
`altstore://source?url=https://raw.githubusercontent.com/bazzadazza72/fladder-develop/refs/heads/develop/altstore.json`
No issue being fixed, just added the shortcut.
Issue Number: N/A
N/A
> Added 'Add to AltStore' button to README

- .github/workflows/build.yml
This updates the RPATHs for the shared libraries and the main executable in the Linux build. Currently, the RPATH points to a path specific to the GitHub Actions runner, which could cause issues. 
Example of current RPATH from the GitHub runner:
```
❯ patchelf --print-rpath ./lib/libdynamic_color_plugin.so
/home/runner/work/Fladder/Fladder/linux/flutter/ephemeral
```
after this change:
```
❯ patchelf --print-rpath ./lib/libdynamic_color_plugin.so
$ORIGIN
```
Changes:
- Add a step in the Actions workflow to set the RPATH for the libraries and the executable using patchelf.
- Changed the RPATH to `$ORIGIN` for the shared libraries and ensure the main executable looks for its libraries in the lib directory next to it by using `$ORIGIN/lib`.
> [Improvement] Fix RPATHs for shared libraries and binary in Linux builds

- lib/screens/login/widgets/discover_servers_widget.dart
Disable discovery of jellyfin servers for web. Because web does not support UDP requests.
Issue Number: #19
> fix: disable server discovery for web

- lib/l10n/app_en.arb
- lib/screens/video_player/components/video_progress_bar.dart
- lib/util/item_base_model/play_item_helpers.dart
When no compatible media format is returned we now properly close the loading indicator and show an error message.
Also fixed a small overflow bug that only caused debug logging.
> fix: Playback not cancelling if no compatible media was found

- lib/l10n/app_en.arb
- lib/models/settings/video_player_settings.dart
- lib/models/settings/video_player_settings.freezed.dart
- lib/models/settings/video_player_settings.g.dart
- lib/providers/library_filters_provider.g.dart
- lib/providers/settings/video_player_settings_provider.dart
- lib/providers/user_provider.g.dart
- lib/screens/settings/player_settings_page.dart
- lib/screens/video_player/components/video_player_options_sheet.dart
- lib/screens/video_player/video_player.dart
- lib/util/device_orientation_extension.dart
Addes a new option in the video player settings where you can select orientations you want to allow
Resolves #20
> feature: Added settings to force the player into certain orientations

- lib/models/playback/direct_playback_model.dart
- lib/models/playback/transcode_playback_model.dart
Fixes a potential thread pool starvation error on the server side when reporting the player's progress, by not sending any `NowPlayingQueue`. The `Next Up` banner/screen still shows up at the end of the content, and I haven't found any side effects.
Resolves #121
> bugfix: Fix sending NowPlayingQueue in progress reports

- .vscode/settings.json
- .vscode/tasks.json
- lib/l10n/app_en.arb
- lib/models/settings/client_settings_model.dart
- lib/models/settings/client_settings_model.freezed.dart
- lib/models/settings/client_settings_model.g.dart
- lib/providers/views_provider.dart
- lib/screens/details_screens/empty_item.dart
- lib/screens/details_screens/movie_detail_screen.dart
- lib/screens/settings/client_settings_page.dart
- lib/screens/shared/media/components/poster_image.dart
- lib/screens/shared/media/components/poster_placeholder.dart
This adds a toggle to show library items that are not supported by Fladder.
It now defaults to not showing these items. This was a complaint on Googles end.
But it also kind of makes sense.
Also the posters now show the title when there is no image available.
Pleasing the Google overlords....
> feat: Improve how unsupported items are shown.

- lib/models/items/season_model.dart
- lib/models/items/season_model.mapper.dart
- lib/providers/items/season_details_provider.dart
When misssing episodes are enabled the episode api endpoint returns specials inside of other seasons for some reason.
This fixes that problem.
> fix: specials being shown in season views

- lib/wrappers/media_control_wrapper.dart
- lib/wrappers/players/lib_mpv.dart
This fixes wakelock being called every time the players state changes to only when pausing/playing the video.
> fix: WakeLock calls now get called properly

- lib/screens/shared/default_title_bar.dart
This fixes the title bar passing the input through the widgets below.
> fix(Desktop): Input no longer passed through titlebar

- docker-compose.yml
This PR removes the `version` attribute from the `docker-compose.yml` file. In its current state, when deployed, the file returns a warning similar to this one:
```
WARN[0000] /home/bailey/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```
The attribute is considered obsolete according to [Docker's documentation](https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete), and removing it will solve some confusion for users that decide to use Docker to run Fladder.
This PR doesn't solve an issue.
*No screenshots are required.*
> chore: Remove `version` attribute from `docker-compose.yml`

- lib/screens/video_player/components/video_progress_bar.dart
- lib/widgets/shared/trick_play_image.dart
This fixes the trick play window wandering off-screen
Resolves #175
> bugfix: Fix trick play overflow

- lib/util/adaptive_layout.dart
This disables switching routers when the size/layout has already been decided.
Resolves #174
> fix: Disabling switching router layouts after setting

- lib/l10n/app_en.arb
- lib/providers/crash_log_provider.dart
- lib/screens/details_screens/book_detail_screen.dart
- lib/screens/details_screens/components/overview_header.dart
- lib/screens/details_screens/episode_detail_screen.dart
- lib/screens/details_screens/movie_detail_screen.dart
- lib/screens/details_screens/season_detail_screen.dart
- lib/screens/details_screens/series_detail_screen.dart
- lib/screens/shared/detail_scaffold.dart
- lib/screens/shared/flat_button.dart
- lib/screens/shared/media/chapter_row.dart
- lib/screens/shared/media/components/chip_button.dart
- lib/screens/shared/media/components/media_header.dart
- lib/screens/shared/media/components/media_play_button.dart
- lib/screens/shared/media/components/next_up_episode.dart
- lib/screens/shared/media/components/small_detail_widgets.dart
- lib/screens/shared/media/external_urls.dart
- lib/util/fladder_image.dart
- lib/util/humanize_duration.dart
- lib/util/string_extensions.dart
- lib/widgets/shared/trick_play_image.dart
Slight re-work of the details  screen for most items.
Makes the background more visible on smaller taller then wider devices.
Improved initial visibility of the play/resume button for items
Resolves #127
> feature: Details screen rework

- lib/screens/settings/client_settings_page.dart
Previously, the "Drag with mouse" switch in the settings would turn on the "AMOLED black" switch and would not respond to input unless the latter switch was turned off.
Now, it works as it should and responds correctly to users enabling the setting.
Resolves #194
*No screenshots/recordings required*
> fix: `Drag with mouse` switch

- lib/main.dart
- lib/models/error_log_model.dart
- lib/providers/crash_log_provider.dart
- lib/screens/crash_screen/crash_screen.dart
- lib/screens/shared/detail_scaffold.dart
Save logs to a .json file in the cache directory and load on application start as to preserve any crashes.
> feature: Save logging to cache directory

- lib/models/playback/playback_model.dart
.STRM files where using the stream url from jellyfin itself despite already being a file that can be streamed.
resolves #57
> fix: STRM files not playing correctly

- lib/screens/library_search/library_search_screen.dart
- lib/screens/shared/detail_scaffold.dart
- lib/screens/shared/nested_scaffold.dart
- lib/widgets/navigation_scaffold/components/floating_player_bar.dart
- lib/widgets/navigation_scaffold/navigation_scaffold.dart
Improvements to floating video player visuals
Fixes floating video player duplicates when layout == Phone
> fix: Hide duplicate floating player in phone layout

- lib/models/playback/direct_playback_model.dart
- lib/models/playback/transcode_playback_model.dart
- lib/providers/service_provider.dart
- lib/providers/video_player_provider.dart
- lib/wrappers/media_control_wrapper.dart
There was a small race condition when reporting playback progress and stopping.
Increase progress report rate to every 10 seconds.
Added a small delay for reporting a stoppped playback.
Resolves #206
> fix: Incorrect playback reporting

- lib/l10n/app_en.arb
- lib/providers/items/episode_details_provider.dart
- lib/screens/details_screens/episode_detail_screen.dart
- lib/screens/details_screens/season_detail_screen.dart
- lib/screens/details_screens/series_detail_screen.dart
- lib/screens/shared/media/people_row.dart
- lib/util/people_extension.dart
Adds guest actors to episode view.
> feature: Add guest actors to episode view

- lib/screens/dashboard/dashboard_screen.dart
- lib/screens/library_search/library_search_screen.dart
- lib/screens/settings/client_sections/client_settings_visual.dart
- lib/screens/settings/client_settings_page.dart
- lib/screens/settings/settings_list_tile.dart
- lib/widgets/navigation_scaffold/navigation_scaffold.dart
- lib/widgets/shared/enum_selection.dart
- lib/widgets/shared/modal_bottom_sheet.dart
> fix: Small bugfixes

- lib/screens/video_player/video_player_controls.dart
The "Ends at" on player controls display end time with date + runtime, so it does not consider the playrate.
> fix: Ends at calculation when playbackrate is not 1x

- lib/screens/video_player/components/video_player_options_sheet.dart
Updated of the playback speed slider to use a step size of 5% and set the maximum speed at 3, i my opinion 10 was a bit hight and only a little partion of the slider was usefull
> feat: playbackrate changes - max set to 3 and smaller steps

- lib/util/video_properties.dart
Add missing video profile types
Resolves #313
> fix: Added missing display profiles

- lib/providers/library_search_provider.dart
Apply shuffle to photo/video libraries
Fix non-video files being added to playback list when playing videos
Resolves #322
> fix: Shuffle play videos

- DEVELOPEMENT.md
- lib/l10n/app_en.arb
- lib/models/account_model.dart
- lib/models/account_model.freezed.dart
- lib/models/items/media_streams_model.dart
- lib/models/playback/playback_model.dart
- lib/providers/service_provider.dart
- lib/providers/user_provider.dart
- lib/screens/settings/player_settings_page.dart
- lib/util/streams_selection.dart
* When switching to the next video using the player button, the stream selections are reset to the default ones (those provided by the server). The app now tries to preserve the current audio and subtitle selections. This avoids falling back to the default stream indexes returned by the server.
To determine if a track matches the previous one, the app uses the scoring logic implemented in the Jellyfin web client (see: [https://github.com/DonutWare/Fladder/discussions/327#discussioncomment-13100519](https://github.com/DonutWare/Fladder/discussions/327#discussioncomment-13100519)).
* Two options have been added in the player settings to choose whether the current track selections should kept if possible. These settings are linked to the Jellyfin user configuration returned by the server …
> Feat player track remember when not default

- .github/workflows/build.yml
This PR changes the first letter of the Mac app to be capital instead, this should be the same as the rest of the apps on other OSes
> chore: Changed case naming for Mac OS App

- lib/l10n/app_en.arb
- lib/models/settings/client_settings_model.dart
- lib/models/settings/client_settings_model.freezed.dart
- lib/models/settings/client_settings_model.g.dart
- lib/providers/update_provider.dart
- lib/providers/update_provider.freezed.dart
- lib/providers/update_provider.g.dart
- lib/screens/settings/about_settings_page.dart
- lib/screens/settings/settings_screen.dart
- lib/screens/settings/widgets/settings_message_box.dart
- lib/screens/settings/widgets/settings_update_information.dart
- lib/util/update_checker.dart
- lib/widgets/navigation_scaffold/components/settings_user_icon.dart
- lib/widgets/navigation_scaffold/components/side_navigation_bar.dart
- pubspec.lock
- pubspec.yaml
Implements a update notification the user can disable if wanted. 
Only gives a notification because updating desktop with the different amount of packages would be less then trivial.
Updates are shown on mobile devices but no notification by default because the update using appstores.
Resolves #154
> feature: Added update notification and download links per platform

- lib/localization_delegates.dart
- lib/main.dart
We have custom translations which can be applied correctly AppLocalizations.delegate.
However some internal flutter widgets try to use a localization that is unsupported this cause the delegates to crash. This fix overwrites the language with English so everything works again.
Possible fix for 
#370
> fix: Overwrite un-supported flutter languages to english

- lib/models/item_base_model.dart
- lib/screens/details_screens/components/overview_header.dart
- lib/screens/shared/media/poster_widget.dart
I tried to keep this as minimal as possible to only the issue(s) presented in the discussion. The only changes were to the precision of the base model item and the overview header. I've provided screenshots of both changes. Additionally, for the poster widget, I'd like some feedback on how to proceed with the changes. Currently, a ternary operator is used to check if `subTitle` exists to ensure that the year is aligned to the left or right. This has an unintended consequence (image 3) of the year being aligned to the left if an entry does not have a `subTitle` but other entries do. This is inconsistent, but the alternative would be that if at least one item in the whole library filtered/displayed has a `subTitle` then the year must be to the right.
Resolves #422
> fix: Standardize precision used in communityRating

- lib/models/item_base_model.dart
- lib/models/items/images_models.dart
The current implementation assumes that Jellyfin's tags are unique and can therefore be used as keys. However, [their logic to create tags](https://github.com/jellyfin/jellyfin/blob/9e36fa426335289b4be90034640ad38b38e3de79/src/Jellyfin.Drawing/ImageProcessor.cs#L409) can lead to duplicate tags across images in the same location (backdrop.jpg, logo.jpg, etc can share the same tag) and same timestamp.
Consider this url example from my server. The tags are the same:
http://localhost:8096/Items/61139a4c4ce0f3e26032c35a7e1adde8/Images/Primary?maxWidth=575&tag=497955eaadd4d4d31609987a736d8374
http://server:8096/Items/61139a4c4ce0f3e26032c35a7e1adde8/Images/Logo?maxWidth=575&tag=497955eaadd4d4d31609987a736d8374
Since the key is assumed to be unique, when we request a logo, we do so with the key. …
> fix: make image cache key unique

- .github/workflows/build.yml
- windows/windows_setup.iss
It seems to be that there is an issue where the `FLADDER_VERSION` environment variable is not defined so the inno installer defaults to latest everytime. This causes several issues such as:
- Inno installer just saying latest
- App Version in Settings/Control Panel saying latest
- Issues with creating new Winget manifests
This PR should fix this issue by overwriting the inno installer  file with the latest version.
Inno installer version not being defined correctly.
Before:
After:
> bug: Fix undefined Inno `AppVersion`

- .github/workflows/build.yml
Adds winget package automation so that winget packages are updated automatically with each release.
For this to work a fork of the https://github.com/microsoft/winget-pkgs repo needs to be done on the DonutWare account, and then a classic token needs to be created (make sure to set it to never expire, unless you want to change it every couple of months) and added to this repo in the secrets section and it needs to be called `WINGET_TOKEN`.
I also decided to keep it to a specific SHA because the latest version v2 is not up to date with the newest changes which are needed for smooth operation.
More info can be found here: https://github.com/vedantmgoyal9/winget-releaser
> chore: Winget package automation

- lib/screens/shared/media/components/poster_image.dart
I propose removing the orange dot that shows the unwatched status on the poster. Actually, before looking at the code, I wasn’t sure what this dot meant, and in my opinion, it’s much clearer this way.
So I propose showing the watched status consistently instead of this dot (as it’s done in the official client).
For shows, I only remove the dot for isolated unwatched episodes.
For movies, I remove the dot and add the mark icon for watched movies.
see pictures bellow.
before 
after
before 
after
> feat: remove the unwatched orange dot and show watched

- lib/l10n/app_en.arb
- lib/screens/settings/player_settings_page.dart
- lib/theme.dart
This pull request improves the player settings page by making keyboard shortcut settings more accessible and organized. The main change is grouping all video hotkey settings under an expandable section labeled "Keyboard shortcuts," making the UI cleaner and easier to navigate for users with pointer input devices. Additionally, a new localization string for "Keyboard shortcuts" has been added.
**UI/UX Improvements:**
* Groups all video hotkey settings under an `ExpansionTile` labeled "Keyboard shortcuts" on the player settings page, improving organization and user experience for pointer input devices (`lib/screens/settings/player_settings_page.dart`).
> feat: make shortcuts list collapsible

- lib/l10n/app_en.arb
- lib/models/settings/client_settings_model.dart
- lib/models/settings/client_settings_model.freezed.dart
- lib/models/settings/client_settings_model.g.dart
- lib/providers/settings/client_settings_provider.dart
- lib/screens/settings/client_sections/client_settings_theme.dart
- lib/screens/shared/detail_scaffold.dart
- pubspec.lock
- pubspec.yaml
Adds the option to use the items generated primary colors as the detail views main colors
> feat: Option to use item's primary colors in details screen
